all:
  vars:
    control_plane_endpoint: 192.168.1.179
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.10, mac: '00:23:24:d6:61:b5', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.1.9, mac: '00:23:24:8b:87:6d', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.1.12, mac: 'd8:cb:8a:23:04:52', disk: sda, network_interface: eth0}
